practice_user_authentication_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('testapp.urls'))
]

testapp/urls.py
from . import views
from django.urls import path
urlpatterns = [
    path('sign/',views.register_view , name='sign_up'),
    path('dash/',views.DashBoardView,name='dashboard'),
    path('login/',views.LoginView, name='Log_In'),
    path('logout/',views.logout_view, name='Log_Out'),
]

testapp/models.py
from django.db import models
# Create your models here.
class Blog(models.Model):
    title=models.CharField(max_length=10)
    dec=models.CharField(max_length=20)

testapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','is_active']

testapp/views.py
from django.shortcuts import render,redirect
from . forms import SignUpForm
from  django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,logout,login
# Create your views here.
def register_view(request):
    if request.method == 'POST':
        fm=SignUpForm(request.POST)
        fm.is_valid()
        fm.save()
        messages.success(request,'your Account well be Created success')
    else:
        fm=SignUpForm()
    return render(request,'testapp/registration.html',{'form':fm})
def LoginView(request):
    if not request.user.is_authenticated:
        if request.method== 'POST':
            fm=AuthenticationForm(request=request,data=request.POST)
            if fm.is_valid():
                uname=fm.cleaned_data['username']
                pword=fm.cleaned_data['password']
                user=authenticate(username=uname,password=pword)
                if user is not None:
                    login(request,user)
                    return redirect('dashboard')
        else:
            fm = AuthenticationForm()
            return render(request,'testapp/login.html',{'form':fm})
    else:
        return redirect('dashboard')
def DashBoardView(request):
    if request.user.is_authenticated:
        return render(request,'testapp/dashboard.html',{'name':request.user.username})
    else:
        return redirect('Log_In')
def logout_view(request):
    logout(request)
    return redirect('Log_In')

templates/testapp/dashboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DashBoard</title>
    <link rel="stylesheet" href="{% static 'testapp/style.css' %}">
</head>
<body>
<h2>Hello Welcome to the my Wold {{ name }}</h2>
{% if perms.testapp.delete_blog %}
<input type="button" value="Delete"><br><br>
    {% else %}
    <h3>No Delete permission</h3>
{% endif %}
{% if perms.testapp.add_blog %}
<input type="button" value="ADD"><br><br>
<br><br>
    {% else %}
    <h3>NO Add Permission</h3>
{% endif %}
<a href="{% url 'Log_Out' %}"><button>LogOut</button></a>
</body>
</html>

templates/testapp/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'testapp/style.css' %}">
</head>
<body>
<form method="post">
    {% csrf_token %}
    {% for fm in form %}
        <p>{{ fm.label_tag }} {{ fm }} {{ fm.errors|striptags }}</p>
    {% endfor %}
    <br>
<input type="submit" value="LogIn">
</form>
</body>
</html>

templates/testapp/registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <link rel="stylesheet" href="{% static 'testapp/style.css' %}">
</head>
<body>
<h3> please register here...!</h3>
<form method="post" novalidate>
    {% csrf_token %}
    {% for fm in form %}
        <p>{{ fm.label_tag }} {{ fm }} {{ fm.errors|striptags }}</p>
    {% endfor %}
    <input type="submit" value="Submit">
</form>
{% if messages %}
    {% for msg in messages %}
        <small {% if msg.tags %} class="{{ msg.tags }}" {% endif %}>{{ msg }}</small>
    {% endfor %}
{% endif %}
<a href="{% url 'Log_In' %}"><button>LogIn</button></a>
</body>
</html>